openapi: 3.0.0

info:
  title: Submit Access Request API
  version: "1.0.0"
  description: >
    Agent tool to submit a new access request.
    Automatically initializes lifecycle processing.

servers:
  - url: https://us-central1-data-engineering-479617.cloudfunctions.net

paths:
  /submit_access_request:
    post:
      summary: Submit a new access request
      operationId: submitAccessRequest
      description: >
        Creates a new access request and starts
        the automated lifecycle flow.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - resource
                - access_level
              properties:
                user_id:
                  type: string
                  example: user123
                resource:
                  type: string
                  example: BigQuery
                access_level:
                  type: string
                  example: read
                justification:
                  type: string
                  example: Required for analytics work
      responses:
        "200":
          description: Access request created
          content:
            application/json:
              schema:
                type: object
                properties:
                  request_id:
                    type: string
                    example: AR-9F32A1BC
                  status:
                    type: string
                    example: created
